### PR TITLE
Handle pointer grabbing abortion / Special invalid focus values / Don't die if destroying fails

### PR DESCRIPTION
**Pull request by baskerville**
Here's a few commits: the oldest is a fix for issue #2.

### CODE REVIEW

**Comment by jimenezrick** [comment]
Nice work! Let me tomorrow take another look before merging everything. I'll probably split some long line by the way.
Do these commits fix all the issues you found out?

**Comment by jimenezrick** [comment]
Personal note for me: try destroy a window already destroyed, sleep after receiving the notification?

**Comment by baskerville** [comment]
Yes, those commits fix all the issues I found so far.

**Comment by jimenezrick** [comment]
I did reproduce the destroying error seeing it with your handy util **xlsw** :smile:  I also redid your last commit, as I preferred to keep the destroy function adding a nice comment explaining the issue.

So Bastien, thanks a lot for you fixes!

**Pull request closed without merging**
